package org.nik.moviecatalog.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;
import java.util.Date;

@ApiModel(value = "Movie Details Model")
public class Movie {

    @ApiModelProperty(value = "Uniquely Identifies a movie. Its auto generated by database sequence", required = true)
    @NotNull
    private Integer movieId;
    @ApiModelProperty(value = "One line description of movie", required = true)
    @NotNull
    private String desc;
    @ApiModelProperty(value = "Release date of movie", required = true)
    @NotNull
    private Date releaseDate;
    @ApiModelProperty(value = "Movie Name", required = true)
    @NotNull
    private String movieName;
    @ApiModelProperty(value = "Genre of a movie", required = true)
    @NotNull
    private String genre;

    public Integer getMovieId() {
        return movieId;
    }

    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Date getReleaseDate() {
        return releaseDate;
    }

    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }

    public String getMovieName() {
        return movieName;
    }

    public void setMovieName(String movieName) {
        this.movieName = movieName;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    @Override
    public String toString() {
        return "Movie{" +
                "movieId='" + movieId + '\'' +
                ", desc='" + desc + '\'' +
                ", releaseDate=" + releaseDate +
                ", movieName='" + movieName + '\'' +
                ", genre='" + genre + '\'' +
                '}';
    }
}
